### ISSUE TITLE
make fail:  src/tree/./updater_distcol-inl.hpp:158: error: `xgboost::tree::SplitEntry::Reduce' is not a valid template argument

### ISSUE THREAD

**Issue by leekun** [dmlc/xgboost#359]
make fail, the message is:
" /usr/bin/make64 MAC=64 no_omp=1
g++ -c -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -DDISABLE_OPENMP  -fPIC     -o updater.o src/tree/updater.cpp
In file included from src/tree/updater.cpp:11:
src/tree/./updater_distcol-inl.hpp:158: error: `xgboost::tree::SplitEntry::Reduce' is not a valid template argument
src/tree/./updater_distcol-inl.hpp:158: error: ISO C++ forbids declaration of `reducer' with no type
src/tree/./updater_distcol-inl.hpp: In member function `virtual void xgboost::tree::DistColMaker<TStats>::Builder::SyncBestSolution(const std::vector<int, std::allocator<int> >&)':
src/tree/./updater_distcol-inl.hpp:147: error: request for member `Allreduce' in `((xgboost::tree::DistColMaker<TStats>::Builder*)this)->xgboost::tree::DistColMaker<TStats>::Builder::reducer', which is of non-class type `int'"

How did it happened?  How can I avoid it?  please tell me please
thank you

**Comment by leekun** [comment]
gcc version is "gcc version 3.4.5 20051201 (Red Hat 3.4.5-2)"
the command is "sh build.sh" in the root directory.

**Comment by leekun** [comment]
build success when I update the version of gcc to 4.8.2.
