### PR TITLE
Remove redundant FindGTest.cmake, Fix gtest include dirs.

### PR DESCRIPTION
**Pull request by trivialfis**
Continue #3469

Gtest is included in CMake before CMake 3.2. We can safely remove it now.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis The CMake test is failing in Travis. You can reproduce this by running
```bash
TASK=cmake_test tests/travis/run_test.sh
```

**Comment by trivialfis** [comment]
@hcho3 Thanks, I'm trying to install GTest in travis. Now that I know I can reproduce the tests in this way, I will configure guix container for testing.

**Comment by trivialfis** [comment]
Hi, @hcho3 can you give me some insight about why the librt is not explicitly linked when building with  gcc-4.8 and glibc-2.2.5 but work before this patch? I am confused which part of this patch triggered the linking failure of dmlc-core on jenkins. Travis built fine though.


> /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: CMakeFiles/dmlc_unit_tests.dir/unittest_thread_group.cc.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: note: 'clock_gettime@@GLIBC_2.2.5' is defined in DSO /lib64/librt.so.1 so try adding it to the linker command line

/lib64/librt.so.1: could not read symbols: Invalid operation

collect2: error: ld returned 1 exit status

make[2]: *** [dmlc-core/test/unittest/dmlc_unit_tests] Error 1

make[1]: *** [dmlc-core/test/unittest/CMakeFiles/dmlc_unit_tests.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

Scanning dependencies of target gpuxgboost

**Comment by hcho3** [comment]
@trivialfis  How did you fix the error?

**Comment by hcho3** [comment]
LGTM

**Comment by trivialfis** [comment]
@hcho3 Sorry for bothering you on this. Can you give me some insight about Jenkins? It seems this PR might broke Jenkins. But I don't understand its behaviour.
Currently, both #3548 and #3557 failed to build on Jenkins with CUDA 8.0. The error is fail to find <gtest/gtest.h> header. It's so weird that Travis and Jenkins with CUDA 9.2 built successfully. I tried to diff the first part of output logs from Jenkins with CUDA 8.0 and 9.0:
On 8.0, there is these two lines:
-- Found the GTest includes: /workspace/gtest/include
-- Found the GTest library: /workspace/gtest/lib/libgtest.a

While on 9.2, the GTest line becomes:
-- Found GTest: /workspace/gtest/lib/libgtest.a

It seems on 8.0, the cmake build is still using old FindGTest, which built successfully.

Is there any cache mechanism I should be aware of?

**Comment by hcho3** [comment]
@trivialfis Just found out that Docker has caching mechanism. Clearing it now.

**Comment by hcho3** [comment]
Indeed, `docker system prune` did the trick.

**Comment by trivialfis** [comment]
@hcho3 Thanks for helping out.
