### PR TITLE
[jvm-packages] Fix Spark 2.2 Support (Amending #3062)

### PR DESCRIPTION
**Pull request by thesuperzapper**
This pull request amends the broken #3062 allow Spark 2.2 to work.

Please note this won't work in Spark <=2.1 as sc.removeSparkListener was implemented in Spark 2.2. (So perhaps a more general method is better, although that is what was attempted in #3062)

This PR fixes: #3208, #3151 and the discussion in #1927.

I do find it strange that #3062 dose not work in Spark 2.2, it's probably due to some sort of public/private issue in the org.apache.spark.scheduler.LiveListenerBus class inheritance (In Spark itself). The error is: `java.lang.NoSuchMethodError: org.apache.spark.scheduler.LiveListenerBus.removeListener(Ljava/lang/Object;)V`

### CODE REVIEW

**Comment by CodingCat** [comment]
thanks for this PR which LGTM

before I merge, I would like to setup a TravisCI test matrix covering Spark 2.2 and 2.3, would you be interested to do that?

**Comment by CodingCat** [comment]
example:https://github.com/graphframes/graphframes/blob/master/.travis.yml

**Comment by thesuperzapper** [comment]
Could someone also try master with Spark 2.1, and see if this `java.lang.NoSuchMethodError` occurs.

**Comment by CodingCat** [comment]
I do not think we will support Spark 2.1 as a too-old version

**Comment by thesuperzapper** [comment]
@CodingCat LGTM? 

In its current state XGBoost-0.72 only supports Spark 2.3+, but with this PR we at least support Spark 2.2+.

An alternative is to do a bit of a hacky case statement and treat pre/post 2.2 separately, do you want me to do that?

With regards to the Travis test matrix, I don't have much experience with that, but its something we need to do.

**Comment by thesuperzapper** [comment]
@CodingCat, this is still an issue on master, if we want 0.8 to support Spark 2.2 this should be merged, be aware that this PR breaks Spark <=2.1.

There is a small chance the existing (non PR) code works if you build XGBoost with 2.2 specified, but I can't get master to build on Spark 2.2 right now.

(I get these errors on build)
```
[INFO] Compiling 14 source files to /xgboost/jvm-packages/xgboost4j-spark/target/classes at 1533555864068
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala:43: error: trait HasWeightCol in package shared cannot be accessed in package org.apache.spark.ml.param.shared
[ERROR]   with BoosterParams with HasWeightCol with HasBaseMarginCol with HasNumClass with ParamMapFuncs
[ERROR]                           ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala:60: error: not found: value weightCol
[ERROR]   def setWeightCol(value: String): this.type = set(weightCol, value)
[ERROR]                                                    ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala:166: error: not found: value weightCol
[ERROR]     val weight = if (!isDefined(weightCol) || $(weightCol).isEmpty) lit(1.0) else col($(weightCol))
[ERROR]                                 ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala:166: error: not found: value weightCol
[ERROR]     val weight = if (!isDefined(weightCol) || $(weightCol).isEmpty) lit(1.0) else col($(weightCol))
[ERROR]                                                 ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostClassifier.scala:166: error: not found: value weightCol
[ERROR]     val weight = if (!isDefined(weightCol) || $(weightCol).isEmpty) lit(1.0) else col($(weightCol))
[ERROR]                                                                                         ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala:44: error: not found: type HasWeightCol
[ERROR]   with LearningTaskParams with HasBaseMarginCol with HasWeightCol with HasGroupCol
[ERROR]                                                      ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala:62: error: not found: value weightCol
[ERROR]   def setWeightCol(value: String): this.type = set(weightCol, value)
[ERROR]                                                    ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala:160: error: not found: value weightCol
[ERROR]     val weight = if (!isDefined(weightCol) || $(weightCol).isEmpty) lit(1.0) else col($(weightCol))
[ERROR]                                 ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala:160: error: not found: value weightCol
[ERROR]     val weight = if (!isDefined(weightCol) || $(weightCol).isEmpty) lit(1.0) else col($(weightCol))
[ERROR]                                                 ^
[ERROR] /xgboost/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala:160: error: not found: value weightCol
[ERROR]     val weight = if (!isDefined(weightCol) || $(weightCol).isEmpty) lit(1.0) else col($(weightCol))
[ERROR]                                                                                         ^
[ERROR] 10 errors found
```

**Comment by CodingCat** [comment]
@thesuperzapper I don't think 0.8 version would be support 2.2 anymore

because we used classes in `org.apache.spark.ml.param.shared` package which were still unreasonably limiting access in 2.3- versions

**Comment by hcho3** [comment]
@CodingCat So 8.0 requires Spark 2.3+?

**Comment by CodingCat** [comment]
yes

**Comment by hcho3** [comment]
Got it. I'll modify http://xgboost.readthedocs.io/en/latest/jvm/index.html, which currently says "Spark 2.0+ required."

**Comment by thesuperzapper** [comment]
@CodingCat in that case, can we merge this, as it won't affect 2.3, but it will allow 2.2 to work (mostly) with the jars built for 2.3.

**Comment by CodingCat** [comment]
@thesuperzapper I don't think moving models to a new package is a good idea, it will break all existing code, 

I think a possible approach is to merge this PR to 0.72 branch which should work with Spark 2.2 without package namespace issue @hcho3 what do you think?

**Comment by hcho3** [comment]
@CodingCat I like the idea. Can you update 0.72 JARs on Maven Central?

**Comment by CodingCat** [comment]
@hcho3 , we cannot update jar for maven, we need to release a new version, either 0.72.1 (sounds strange) or 0.73

**Comment by thesuperzapper** [comment]
@CodingCat @hcho3 just for reference, there is little point backporting this to 0.72, as if you build 0.72 with Spark 2.2 specified in the pom.xml,  the error doesn't happen, (so perhaps we should just publish a Spark 2.2 built jar to maven?)

What I was suggesting was that we merge this into 0.8, so that the 0.8 jars we build for Spark 2.3 work on Spark 2.2, as in my testing, models still successfully train/run on Spark 2.2 if this PR is applied.

**Comment by hcho3** [comment]
@thesuperzapper You previously said that

> In its current state XGBoost-0.72 only supports Spark 2.3+, but with this PR we at least support Spark 2.2+.

So wouldn't backporting this to 0.72 have some benefit?

**Comment by thesuperzapper** [comment]
> > In its current state XGBoost-0.72 only supports Spark 2.3+, but with this PR we at least support Spark 2.2+.

> So wouldn't backporting this to 0.72 have some benefit?

@hcho3 Yea, I was wrong, what I should have said was it lets the jars built for 2.3 work with 2.2. (I.e. the maven jars)

@CodingCat I agree that we should merge this and distributed jars built on 2.3, with a proviso that 2.2 may not behave as expected.

**Comment by hcho3** [comment]
Since this commit is a one-liner, I'm going to go ahead and merge this. The JVM doc will still specify Spark 2.3+ as minimum requirement.
