### ISSUE TITLE
xgboost 1.5.0 gives 'XGBModel' object has no attribute 'enable_categorical' error

### ISSUE THREAD

**Issue by lmocsi** [dmlc/xgboost#7423]
I've created an XGBClassifier model in xgboost 1.4.2, and saved it with pickle.<br>
Applying it on new data works fine in 1.4.2.<br>
However, after upgrading to xgboost 1.5.0, I get the bellow error, when applying the model to new data:

    ...
    model = pickle.load(open(modelfile, "rb"))
    y_pred = model.predict_proba(x)[:,1]  # probability of 1s

scikit-learn==0.24.2
scikit-learn-intelex==2021.3.0
xgboost==1.4.2

>Traceback (most recent call last):
> File "xxx.py", line 174, in <module>
>&nbsp;    y_pred = model.predict_proba(x)[:,1]  # probability of 1s
> File "C:\Program Files\Python38\lib\site-packages\xgboost\sklearn.py", line 1348, in predict_proba
>&nbsp;    class_probs = super().predict(
> File "C:\Program Files\Python38\lib\site-packages\xgboost\sklearn.py", line 879, in predict
>&nbsp;    if self._can_use_inplace_predict():
> File "C:\Program Files\Python38\lib\site-packages\xgboost\sklearn.py", line 811, in _can_use_inplace_predict
>&nbsp;    predictor = self.get_params().get("predictor", None)
> File "C:\Program Files\Python38\lib\site-packages\xgboost\sklearn.py", line 505, in get_params
>&nbsp;    params.update(cp.__class__.get_params(cp, deep))
> File "C:\Program Files\Python38\lib\site-packages\xgboost\sklearn.py", line 502, in get_params
>&nbsp;    params = super().get_params(deep)
> File "C:\Program Files\Python38\lib\site-packages\sklearn\base.py", line 195, in get_params
>&nbsp;    value = getattr(self, key)
>AttributeError: 'XGBModel' object has no attribute 'enable_categorical'

Is it a bug? Or a feature, and I should stick to xgboost==1.4.2 when running the model on new data?

**Comment by trivialfis** [comment]
Hi, the pickle format is not stable as explained in https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html 

You can use `save_model` for exporting a stable model format.
