### PR TITLE
Fix R package build with CMake 3.13

### LINKED ISSUE #5894: Failed to build R package.
After #5871 I can't build R package on my local machine with link time error:

```
/usr/bin/ld: ../../R-package/CMakeFiles/xgboost-r.dir/src/init.c.o: in function `R_init_xgboost':
/home/fis/Workspace/XGBoost/xgboost/R-package/src/init.c:83: undefined reference to `R_registerRoutines'
/usr/bin/ld: /home/fis/Workspace/XGBoost/xgboost/R-package/src/init.c:84: undefined reference to `R_useDynamicSymbols'
/usr/bin/ld: ../../R-package/CMakeFiles/xgboost-r.dir/src/xgboost_R.cc.o: in function `XGCheckNullPtr_R':
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:41: undefined reference to `R_ExternalPtrAddr'
/usr/bin/ld: /home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:41: undefined reference to `Rf_ScalarLogical'
/usr/bin/ld: ../../R-package/CMakeFiles/xgboost-r.dir/src/xgboost_R.cc.o: in function `_DMatrixFinalizer(SEXPREC*)':

...
```

R: 3.6.1
CMake: 3.13.4
GCC: gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

### PR DESCRIPTION
**Pull request by hcho3**
Fixes #5894. 

The dependency graph in XGBoost build looks like this:
```
xgboost-r  ---> objxgboost  ---> xgboost
```
Previously, the R lib was linked to `xgboost-r` with `PRIVATE` designation, and if CMake 3.13 was used, the R lib requirement would not be progagated to `xgboost` target, so that is why the build failed in #5894.

This PR make the R lib a `PUBLIC` requirement of `xgboost-r`, so the build will work correctly with CMake 3.13.

Note that the fix does not apply to CMake 3.14 or newer. The Release Note for CMake 3.14 says:
> Object library linking has been fixed to propagate private link libraries of object libraries to consuming targets.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis Can you try running it in your machine?

**Comment by trivialfis** [comment]
@hcho3 OMP flags are not propagated:

```
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:80: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   80 |   #pragma omp parallel for schedule(static)
      | 
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:114: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
  114 |   #pragma omp parallel for schedule(static)
      | 
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:165: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
  165 |     #pragma omp parallel for schedule(static)
      | 
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:174: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
  174 |     #pragma omp parallel for schedule(static)
      | 
/home/fis/Workspace/XGBoost/xgboost/R-package/src/xgboost_R.cc:268: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
  268 |   #pragma omp parallel for schedule(static)
```

**Comment by hcho3** [comment]
@trivialfis Did you enable `-Wall` flag? I had to add it to see the OpenMP warning.

**Comment by trivialfis** [comment]
Yup.  The flag is quite useful for me.

**Comment by hcho3** [comment]
@trivialfis Do you think it would be useful to run builds with `-Wall` flag in Linux CI builds?

**Comment by trivialfis** [comment]
Then we might also need to make some changes to rabit.

**Comment by trivialfis** [comment]
We can do something like `-Wall -Werror` to make compilation fail.  It might be too restricted, as currently on hist tree method, there's a warning about memcpy.

**Comment by hcho3** [comment]
> Then we might also need to make some changes to rabit.

I don't think it's necessary. We can just add `target_compile_option(rabit PRIVATE -Wall)`. We already add `-D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE` to rabit and dmlc-core in the root CMakeLists.txt.

**Comment by hcho3** [comment]
> We can do something like -Wall -Werror to make compilation fail. It might be too restricted, as currently on hist tree method, there's a warning about memcpy.

Eventually we should drive an effort to reduce compiler warnings over time. Visual Studio is currently showing ~ 1000 warnings for XGBoost, and I'm sure not all of it is a false alarm.

**Comment by trivialfis** [comment]
```
[ 16%] Built target dmlc_unit_tests
/home/fis/Workspace/XGBoost/xgboost/rabit/src/allreduce_robust.cc: In member function ‘int rabit::engine::AllreduceRobust::SetBootstrapCache(const string&, const void*, size_t, size_t)’:
/home/fis/Workspace/XGBoost/xgboost/rabit/src/allreduce_robust.cc:102:7: warning: variable ‘index’ set but not used [-Wunused-but-set-variable]
   int index = -1;
       ^~~~~
/home/fis/Workspace/XGBoost/xgboost/rabit/src/allreduce_robust.cc: In member function ‘int rabit::engine::AllreduceRobust::SetBootstrapCache(const string&, const void*, size_t, size_t)’:
/home/fis/Workspace/XGBoost/xgboost/rabit/src/allreduce_robust.cc:102:7: warning: variable ‘index’ set but not used [-Wunused-but-set-variable]
   int index = -1;
       ^~~~~
/home/fis/Workspace/XGBoost/xgboost/rabit/src/allreduce_robust.cc: In member function ‘int rabit::engine::AllreduceRobust::SetBootstrapCache(const string&, const void*, size_t, size_t)’:
/home/fis/Workspace/XGBoost/xgboost/rabit/src/allreduce_robust.cc:102:7: warning: variable ‘index’ set but not used [-Wunused-but-set-variable]
   int index = -1;
```

**Comment by hcho3** [comment]
Let me file another PR to add CMake option for enabling more warnings. We don't have to add `-Werror` right now.

**Comment by trivialfis** [comment]
@hcho3 

> Eventually we should drive an effort to reduce compiler warnings over time

I would love that.  Most of the msvc warnings are about type convection.  I spent some effort to unify the types on XGBoost, but still a long way to go.

**Comment by trivialfis** [comment]
@hcho3 You can reproduce some msvc warnings with gcc by specifying `-Werror`.

**Comment by trivialfis** [comment]
Probably just pick them from https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html .

**Comment by hcho3** [comment]
#5897 adds CMake option `ENABLE_ALL_WARNINGS`.

**Comment by trivialfis** [comment]
Tested.  Looks good.  Thanks for the quick fix!
