### PR TITLE
[doc] Add Spark 4.0 compatibility warning for JVM packages

### PR DESCRIPTION
**Pull request by wbo4958**
## Summary

- Add a warning to the XGBoost4J-Spark tutorial (`doc/jvm/xgboost4j_spark_tutorial.rst`) about Spark 4.0.0 binary incompatibility
- Add a "Spark 4.0 Compatibility" section to the migration guide (`doc/jvm/xgboost_spark_migration.rst`)

## Context

Apache Spark 4.0.0 introduced a breaking change to `org.apache.spark.ml.param.Param` constructor ([SPARK-52259](https://issues.apache.org/jira/browse/SPARK-52259)), which causes `NoSuchMethodError` when instantiating any XGBoost estimator (e.g., `XGBoostClassifier`, `XGBoostRegressor`). This affects all third-party ML libraries that use `Param`.

**Test results:**
| Spark Version | Result |
|---|---|
| 4.0.0 | **FAIL** — `NoSuchMethodError` on `Param` constructor |
| 4.1.0 | **PASS** — XGBoostClassifier trains and predicts correctly |

The upstream fix is included in Spark 4.0.1 (released 2025-09-02) and Spark 4.1.0. XGBoost4J-Spark JARs built against Spark 3.5 work on Spark 4.0.1+ without any code changes.

This PR adds documentation warnings so users know to avoid Spark 4.0.0 and use Spark 4.0.1 or later.

## Related

- #11510 — [discussion] How to support Spark 4.0
- #11498 — [jvm-packages] Upgrade to Java 17+
- [SPARK-52259](https://issues.apache.org/jira/browse/SPARK-52259) — Fix Param class binary compatibility

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by trivialfis** [comment]
I think a simple troubleshooting note should be sufficient

**Comment by wbo4958** [comment]
Hi @trivialfis, I didn't see there's a troubleshooting section, where do you suggest to add?

**Review by trivialfis — APPROVED** [review]
