### ISSUE TITLE
Error build with gcc 6.1.0 on Mac OS X

### ISSUE THREAD

**Issue by clavichord93** [dmlc/xgboost#1268]
GCC in Homebrew has upgraded to 6.1.0 and building xgboost with g++-6 will lead to the following error:

`
In file included from src/tree/tree_model.cc:8:0:
src/tree/./param.h: In member function 'double xgboost::tree::TrainParam::CalcGain(double, double) const':
src/tree/./param.h:126:53: error: call of overloaded 'abs(double&)' is ambiguous
         return - 2.0 * (ret + reg_alpha * std::abs(w));
                                                     ^
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/ext/string_conversions.h:41:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/cstdlib:75:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/ext/string_conversions.h:41,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
/usr/include/stdlib.h:129:6: note: candidate: int abs(int)
 int  abs(int) __pure2;
      ^~~
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/ext/string_conversions.h:41:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
In file included from src/tree/tree_model.cc:8:0:
src/tree/./param.h: In member function 'double xgboost::tree::TrainParam::CalcGain(double, double, double, double) const':
src/tree/./param.h:138:51: error: call of overloaded 'abs(double&)' is ambiguous
       return - 2.0 * (ret + reg_alpha * std::abs(w));
                                                   ^
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/ext/string_conversions.h:41:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/cstdlib:75:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/ext/string_conversions.h:41,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
/usr/include/stdlib.h:129:6: note: candidate: int abs(int)
 int  abs(int) __pure2;
      ^~~
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/ext/string_conversions.h:41:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/string:52,
                 from dmlc-core/include/dmlc/io.h:9,
                 from include/xgboost/tree_model.h:10,
                 from src/tree/tree_model.cc:6:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
g++-6 -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -MM -MT build/tree/tree_updater.o src/tree/tree_updater.cc >build/tree/tree_updater.d
g++-6 -c -std=c++0x -Wall -O3 -msse2  -Wno-unknown-pragmas -funroll-loops -Iinclude   -Idmlc-core/include -Irabit/include -fPIC -fopenmp -c src/tree/tree_updater.cc -o build/tree/tree_updater.o
make: *** [build/tree/tree_model.o] Error 1
make: *** Waiting for unfinished jobs....
`

How to fix this?

**Comment by clavichord93** [comment]
I tried to add `#include <cmath>` in `src/tree/param.h` and succeed.

**Comment by ezietsman** [comment]
Yup, adding the cmath include worked for me too.

**Comment by chechir** [comment]
me three :+1:

**Comment by thirdwing** [comment]
@clavichord93 A PR will be appreciated.
