### ISSUE TITLE
Migrating from dask-ml to xgboost.dask

### ISSUE THREAD

**Issue by sandys** [dmlc/xgboost#5347]
hi guys,
we are planning to migrate from dask-ml's xgboost interface to xgboost.dask. 

We **extensively** use Scikit pipelines and Gridsearchcv. dask-ml's internal datastructures dont support this and throw an error.
a trivial example that gives an error in dask-ml is 

``` python
import dask.dataframe as dd
import numpy as np
import pandas as pd
from dask_ml.model_selection import GridSearchCV
from dask_ml.xgboost import XGBClassifier
from distributed import Client
from sklearn.datasets import load_iris

if __name__ == '__main__':

    client = Client()

    data = load_iris()

    x = pd.DataFrame(data=data['data'], columns=data['feature_names'])
    x = dd.from_pandas(x, npartitions=2)

    y = pd.Series(data['target'])
    y = dd.from_pandas(y, npartitions=2)

    estimator = XGBClassifier(objective='multi:softmax', num_class=4)
    grid_search = GridSearchCV(
        estimator,
        param_grid={
            'n_estimators': np.arange(15, 105, 15)
        },
        scheduler='threads'
    )

    grid_search.fit(x, y)
    results = pd.DataFrame(grid_search.cv_results_)
    print(results.to_string())
```

we are unable to get this to run in xgboost.dask . Could someone help out on the right example here ?
I'm particularly talking about https://github.com/dmlc/xgboost/blob/master/demo/dask/sklearn_cpu_training.py

**Comment by trivialfis** [comment]
Yup.  Working with dask ml is one of the priority for XGBoost s dask interface.  Thanks for rasing the issue here.  I will look into it.

**Comment by trivialfis** [comment]
Some notes for the future:

- It seems dask ml doesn't support dask dataframe or at least treat it specially: https://github.com/dask/dask-ml/blob/4c52e2d23575470c383cb208f650eb59913283fa/dask_ml/model_selection/utils.py#L87
- When using `da.from_array`, the data passed to XGBoost is a numpy array instead of a dask array.

**Comment by sandys** [comment]
I have a currently open bug tracking this issue

https://github.com/dask/dask-ml/issues/521

**Comment by sandys** [comment]
> Yup. Working with dask ml is one of the priority for XGBoost s dask interface. Thanks for rasing the issue here. I will look into it.

@trivialfis could you clarify how do you see the long term evolution here - does xgboost.dask become the official interface or dask-ml ? we would prefer to follow the official xgboost stand here.

**Comment by trivialfis** [comment]
The XGBoost interface will take over.  We will try to be compatible with other dask ml functionalities as much as possible, just like being compatible with scikit learn.

**Comment by sandys** [comment]
Acknowledged and thanks for this.

We will then move to the Dask interface.

Is the Xgboost.dask interface already compatible with scikit ? We have not
been able to make it work with gridsearchcv in a distributed way.

**Comment by trivialfis** [comment]
Sorry for the ambiguity, when I said scikit learn I meant single node training.  For distributed interface we will target dask-ml.

**Comment by sandys** [comment]
Hi
Bit confused here - I'm specifically asking in context of Dask
interoperability.

Whether I am running Dask on one machine vs hundred shouldn't make a
difference right ?

We would like to use the same code for single machine (for e.g. my laptop
which has a single Dask node) and production (which has hundred Dask nodes)

It will be unproductive/error prone to use different libraries for
different number of machines.

**Comment by trivialfis** [comment]
Yup.  The dask interface should be compatible with dask ml.

**Comment by sandys** [comment]
Apologise for asking again - will the Xgboost.dask interface support both
single machine Dask and distributed Dask training usecases ?

Because dask-ml does that (minus a few bugs).

The goal is to either use xgboost.dask or dask-ml.
It will not be viable to use both.

**Comment by trivialfis** [comment]
@sandys 

There are two different components in `dask-ml`.  First is the `Scikit-Learn` basic functionality and its interface, like grid search.  And then the second part is library specific wrappers like wrapper for XGBoost.

The XGBoost dask interface is taking over from the original XGBoost wrapper in `dask-ml` (the second component).

> will the Xgboost.dask interface support both single machine Dask and distributed Dask training usecases ?

Yes.  As long as a feature is supported by dask-ml, we stride to support it.

**Comment by trivialfis** [comment]
Hope that helps.

**Comment by sandys** [comment]
Understood. So if we want to use the gridsearchcv and scikit functionality,
we have to use via dask-ml.

Has the new interface already been patched into dask-ml ?

**Comment by TomAugspurger** [comment]
In a quick test, I noticed that the `xgboost.XGBoostClassifer` doesn't yet work with dask arrays.

```python
In [1]: from distributed import Client

In [2]: import dask_ml.datasets

In [3]: import xgboost

In [4]: client = Client()

In [5]: X, y = dask_ml.datasets.make_classification(n_features=100, n_samples=100_000, chunks=10_000)

In [6]: clf = xgboost.XGBClassifier()

In [7]: clf.fit(X, y)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-b0953fbb1d6e> in <module>
----> 1 clf.fit(X, y)

~/miniconda3/envs/xgboost=1.0.1/lib/python3.8/site-packages/xgboost/sklearn.py in fit(self, X, y, sample_weight, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, callbacks)
    676         evals_result = {}
    677         self.classes_ = np.unique(y)
--> 678         self.n_classes_ = len(self.classes_)
    679
    680         xgb_options = self.get_xgb_params()

TypeError: 'float' object cannot be interpreted as an integer
```

That's because `np.unique(dask.array.Array)` returns a Dask array with unknown (NaN) length, so `len` raises.

Typically, scikit-learn APIs accept classes as a keyword argument to `fit`, but the version in xgboost doesn't.

```python
In [8]: clf.fit(X, y, classes=[0, 1])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-15b6a6f7c523> in <module>
----> 1 clf.fit(X, y, classes=[0, 1])

TypeError: fit() got an unexpected keyword argument 'classes'
```

**Comment by trivialfis** [comment]
Use `xgboost.dask` instead.

**Comment by sandys** [comment]
Hi Tom
I'm referring to your work on https://github.com/dask/dask-ml/pull/612 as
well. This is very important to us.

Will it work with Xgboost 1.0 ? I'm referring to the comment you just made.
Not sure if there's something else that needs to happen

**Comment by TomAugspurger** [comment]
I'm not sure either, but it seems like it should be OK. Can you test and
see?

**Comment by sandys** [comment]
@TomAugspurger this throws error

`
import xgboost 
import dask_ml.datasets
import dask.dataframe as dd
import dask.array as da
import numpy as np
from dask_ml.model_selection import GridSearchCV
from dask.distributed import Clientclient = Client()
X, y = dask_ml.datasets.make_classification(n_features=100, n_samples=100_000, chunks=10_000)
parameters = {'eta': [0.1, 0.2], 'max_depth': [6, 7]}
xgb = xgboost.dask.DaskXGBClassifier()
clf = GridSearchCV(xgb, parameters, scheduler='threads', cache_cv=False)
clf.fit(X,y)
`

> TypeError: Expecting <class 'dask.dataframe.core.DataFrame'> or <class 'dask.array.core.Array'>.  Got <class 'numpy.ndarray'>

**Comment by TomAugspurger** [comment]
Thanks. Can you debug what's going on?

**Comment by sandys** [comment]
The gridsearchcv in Dask-ml expects a different kind of input.

This works with sklearn gridsearchcv. But I'm not sure if it distributes.

**Comment by sandys** [comment]
```
import xgboost 
import dask_ml.datasets
import dask.dataframe as dd
import dask.array as da
import numpy as np
from dask_ml.model_selection import GridSearchCV
from dask.distributed import Clientclient = Client(n_workers=3, threads_per_worker=1)
clientX, y = dask_ml.datasets.make_classification(n_features=100, n_samples=100_000, chunks=10_000)
parameters = {'eta': [0.1, 0.2], 'max_depth': [6, 7]}
xgb = xgboost.XGBClassifier()
clf = GridSearchCV(xgb, parameters, scheduler='distributed')
clf.cv_results_
```

This kinda works.
It fails if I change XGBClassifier to DaskXGBClassifier.

```
WARNING:dask_ml.model_selection._search:('daskxgbclassifier-fit-score-0eac988fcd50f1b966753744ffa7057c', 0, 0) has failed... retrying
WARNING:dask_ml.model_selection._search:('daskxgbclassifier-fit-score-0eac988fcd50f1b966753744ffa7057c', 1, 0) has failed... retrying
```

It keeps failing and retrying.

**Comment by trivialfis** [comment]
There are some conflicts here.  Dask ml is designed to scale up single node libraries like scikit learn, but XGBoost dask itself is a distributed library.

**Comment by sandys** [comment]
Thanks for replying.

What we are looking for is Xgboost in distributed mode (Dask) being able to
work with scikit libraries like gridsearchcv (which should themselves be
distributed)

If we use  DaskXGBClassifier , then how do I get it work with gridsearchcv
in distributed mode ?

A bit confused on how to get the entire flow to be distributed.

Thanks .

**Comment by jborchma** [comment]
So I have also run into an issue when using `DaskXGBoostClassifier`. Here is a minimal example based on the dask example in the repo:

```python
from sklearn import datasets
import pandas as pd
import dask.dataframe as dd
import xgboost
from dask.distributed import Client, LocalCluster

def main(client):
    n_features = 13
    random_state = 75
    n_samples = 100000
    n_classes = 2
    n_informative = 3
    X, y = datasets.make_classification(
        n_features=n_features,
        n_redundant=3,
        n_repeated=0,
        n_informative=n_informative,
        flip_y=0,
        n_clusters_per_class=2,
        n_classes=n_classes,
        n_samples=n_samples,
        random_state=random_state
    )
    train_data = pd.DataFrame(X)
    train_data["target"] = y
    train_data.columns = train_data.columns.astype(str)
    features = [column for column in train_data.columns if column != "target"]

    train_dask = dd.from_pandas(train_data, chunksize=10000)
    X = train_dask[features]
    y = train_dask["target"]


    model = xgboost.dask.DaskXGBClassifier(client)
    model.fit(X, y, eval_set=[(X, y)])           # returning the trained model
    print(model._Booster.feature_names)


if __name__ == '__main__':
    # or use other clusters for scaling
    with LocalCluster(n_workers=4, threads_per_worker=1) as cluster:
        with Client(cluster) as client:
            main(client)
```

It generates a pretty long error trace:

```
Traceback (most recent call last):
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/worker.py", line 3277, in dumps_function
    result = cache_dumps[func]
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/utils.py", line 1518, in __getitem__
    value = super().__getitem__(key)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/collections/__init__.py", line 1027, in __getitem__
    raise KeyError(key)
KeyError: <function train.<locals>.dispatched_train at 0x1265d5680>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 38, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
AttributeError: Can't pickle local object 'train.<locals>.dispatched_train'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dask_test.py", line 73, in <module>
    main(client)
  File "dask_test.py", line 65, in main
    model.fit(X, y, eval_set=[(X, y)])           # returning the trained model
  File "/Users/jborchma/github/xgboost/python-package/xgboost/dask.py", line 653, in fit
    evals=evals)
  File "/Users/jborchma/github/xgboost/python-package/xgboost/dask.py", line 418, in train
    workers=workers)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/client.py", line 1698, in map
    actors=actor,
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/client.py", line 2511, in _graph_to_futures
    "tasks": valmap(dumps_task, dsk3),
  File "cytoolz/dicttoolz.pyx", line 179, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 204, in cytoolz.dicttoolz.valmap
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/worker.py", line 3315, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/worker.py", line 3279, in dumps_function
    result = pickle.dumps(func)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1148, in dumps
    cp.dump(obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 491, in dump
    return Pickler.dump(self, obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 566, in save_function
    return self.save_function_tuple(obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 780, in save_function_tuple
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 656, in save_reduce
    self._batch_appends(listitems)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 566, in save_function
    return self.save_function_tuple(obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 780, in save_function_tuple
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/Users/jborchma/miniconda3/envs/xgboost/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle generator objects
```

**Comment by trivialfis** [comment]
Let me take a look.

**Comment by trivialfis** [comment]
@jborchma  Please remove `client` as the parameter.

**Comment by trivialfis** [comment]
@sandys  Sorry for the confusion here.  It's something I need to address.  I have been syncing up with the dask ml recently.  Will keep you posted here.

**Comment by sandys** [comment]
@trivialfis thank you! i will be standing by to run any tests, etc that you need.  Being able to run a whole distributed scikit pipeline is of high degree of importance to us.

**Comment by jborchma** [comment]
> @jborchma Please remove `client` as the parameter from `DaskXGBClassifier`.

Oh wow, thanks for the quick fix. My error!

**Comment by trivialfis** [comment]
@sandy You can use scikit-learn gridsearch with xgboost-dask now.

**Comment by sandys** [comment]
Hi
Thanks!
Are you referring to dask-ml gridsearchcv ?

Any chance of a sample code, because not very clear on the structure.

**Comment by trivialfis** [comment]
@sandys No I'm referring to scikit-learn.  dask-ml is used to scale up single node algorithms (AFAIK), XGBoost itself can distribute data among workers and do the synchronization.  Eventually I want to have both models of distributed pipeline working in one interface, but so far we have 2 of them.

For using `scikit-learn`(single-node) grid searching with `xgboost.dask`(distributed):

``` Python
    from sklearn.model_selection import GridSearchCV
    with LocalCluster(n_workers=4) as cluster:
        with Client(cluster) as client:
            X, y = generate_array()
            reg = xgb.dask.DaskXGBRegressor(learning_rate=0.1,
                                            tree_method='hist')
            reg.client = client
            model = GridSearchCV(reg, {'max_depth': [2, 4],
                                       'n_estimators': [5, 10]},
                                 cv=2, verbose=1, iid=True)
            model.fit(X, y)
```

Another combination is `dask-ml`(distributed) and `xgboost.sklearn`(single-node), which I'm not familiar yet.

You can see the conflict we are trying to resolve: only one of them can be distributed.

**Comment by sandys** [comment]
Thanks for the reply.

I had one doubt. In your "For using scikit-learn(single-node) grid
searching with xgboost.dask(distributed) " code example...will the
gridsearchcv be distributed on the Dask nodes ?
Or will it run in a single node only.

**Comment by trivialfis** [comment]
Yes.  The data is distributed across workers and XGBoost syncs the gradient between workers during training.

**Comment by trivialfis** [comment]
Prefer https://github.com/dmlc/xgboost/issues/6525 instead.
