### ISSUE TITLE
XGBoost fails to build because of missing -pthread and -fopenmp cmake directives

### ISSUE THREAD

**Issue by tmalbonph** [dmlc/xgboost#4415]
1. -pthread is not included into CMAKE_CXX_FLAGS
2. -fopenmp is not included into CMAKE_CXX_FLAGS

To fix the error; had to modify CMakeLists.txt to include the following

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")

if (USE_OPENMP)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
endif (USE_OPENMP)

**Comment by hcho3** [comment]
Can you post the error message you saw?

**Comment by hcho3** [comment]
@tmalbonph We have an automated testing system that compiles every version of XGBoost. The latest log shows both [`-fopenmp` flag](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/174/pipeline/104#step-129-log-565) and [`-lpthread` flag](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/174/pipeline/104#step-129-log-748).

**Comment by tmalbonph** [comment]
> @tmalbonph We have an automated testing system that compiles every version of XGBoost. The latest log shows both [`-fopenmp` flag](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/174/pipeline/104#step-129-log-565) and [`-lpthread` flag](https://xgboost-ci.net/blue/organizations/jenkins/xgboost/detail/master/174/pipeline/104#step-129-log-748).


### https://github.com/dmlc/xgboost/issues/4415

### Check out xgboost commit 77c03538b0db2e3608ef07ddcf9b48325584dbee

```bash
cd /Users/test
git clone git@github.com:dmlc/xgboost.git

lsb_release -a
#Distributor ID:	Ubuntu
#Description:	Ubuntu 16.04.6 LTS
#Release:	16.04
#Codename:	xenial

cd xgboost
git checkout 77c03538b0db2e3608ef07ddcf9b48325584dbee
git log -1
#commit 77c03538b0db2e3608ef07ddcf9b48325584dbee
#Author: Jiaming Yuan <jm.yuan@outlook.com>
#Date:   Sat Apr 27 13:03:23 2019 +0800
#
#    Fix node reuse. (#4404)
#    
#    * Reinitialize `_sindex` when reallocating a deleted node.

```

### Update the submodule
```bash
git submodule update --init --recursive

Cloning into 'cub'...
remote: Enumerating objects: 32671, done.
remote: Total 32671 (delta 0), reused 0 (delta 0), pack-reused 32671
Receiving objects: 100% (32671/32671), 16.53 MiB | 732.00 KiB/s, done.
Resolving deltas: 100% (28644/28644), done.
Checking connectivity... done.
Submodule path 'cub': checked out 'b20808b1b04ec3d6a625e51fbc1eb76f337754ad'
Cloning into 'dmlc-core'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 5588 (delta 5), reused 14 (delta 4), pack-reused 5560
Receiving objects: 100% (5588/5588), 1.41 MiB | 574.00 KiB/s, done.
Resolving deltas: 100% (3374/3374), done.
Checking connectivity... done.
Submodule path 'dmlc-core': checked out '13d5acb8ba7e79550bbf2f730f1a3944ff0fa68b'
Cloning into 'rabit'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 3313 (delta 7), reused 11 (delta 4), pack-reused 3283
Receiving objects: 100% (3313/3313), 977.69 KiB | 515.00 KiB/s, done.
Resolving deltas: 100% (2145/2145), done.
Checking connectivity... done.
Submodule path 'rabit': checked out 'a429748e244f67f6f144a697f3aa1b1978705b11'
```

### Build the xgboost

```bash
mkdir linux_x64
cd linux_x64
cmake ..
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Release' as none was specified.
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- /Users/test/xgboost/dmlc-core/cmake/build_config.h.in -> /Users/test/xgboost/dmlc-core/include/dmlc/build_config.h
-- Performing Test SUPPORT_CXX11
-- Performing Test SUPPORT_CXX11 - Success
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT
-- Performing Test XGBOOST_MM_PREFETCH_PRESENT - Success
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT
-- Performing Test XGBOOST_BUILTIN_PREFETCH_PRESENT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/test/xgboost/linux_x64
```

### Compile it

```bash
make --jobs=2 > /Users/test/xgboost-error-1.log 2>&1
tail -f /Users/test/xgboost-error-1.log
...
[ 62%] Building CXX object dmlc-core/CMakeFiles/dmlc.dir/src/build_config.cc.o
/Users/test/xgboost/dmlc-core/src/build_config.cc:14:6: warning: #warning "Redefining fopen64 with std::fopen" [-Wcpp]
     #warning "Redefining fopen64 with std::fopen"
      ^
...
[ 98%] Built target xgboost
[100%] Linking CXX executable ../xgboost
src/CMakeFiles/objxgboost.dir/c_api/c_api.cc.o: In function `XGDMatrixCreateFromCSCEx._omp_fn.1':
c_api.cc:(.text+0x15): undefined reference to `omp_get_num_threads'
c_api.cc:(.text+0x1d): undefined reference to `omp_get_thread_num'
src/CMakeFiles/objxgboost.dir/c_api/c_api.cc.o: In function `PrefixSum(unsigned long*, unsigned long) [clone ._omp_fn.2]':
c_api.cc:(.text+0x100): undefined reference to `omp_get_thread_num'
c_api.cc:(.text+0x107): undefined reference to `omp_get_num_threads'
c_api.cc:(.text+0x10f): undefined reference to `GOMP_single_start'
c_api.cc:(.text+0x147): undefined reference to `GOMP_barrier'
...
dmlc-core/libdmlc.a(io.cc.o): In function `dmlc::io::CachedInputSplit::InitPreprocIter()':
io.cc:(.text._ZN4dmlc2io16CachedInputSplit15InitPreprocIterEv[_ZN4dmlc2io16CachedInputSplit15InitPreprocIterEv]+0x89d): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/runxgboost.dir/build.make:178: recipe for target '../xgboost' failed
make[2]: *** [../xgboost] Error 1
CMakeFiles/Makefile2:145: recipe for target 'CMakeFiles/runxgboost.dir/all' failed
make[1]: *** [CMakeFiles/runxgboost.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

### Copy of "xgboost-error-1.log" attach to this post
[xgboost-error-1.log](https://github.com/dmlc/xgboost/files/3125736/xgboost-error-1.log)

**Comment by hcho3** [comment]
It appears that XGBoost doesn't compile with CMake older than version 3.12. Let me take a look.

**Comment by tmalbonph** [comment]
> It appears that XGBoost doesn't compile with CMake older than version 3.12. Let me take a look.

@hcho3 
It compile, the error is during the linking process; missing library for pthread and fopenmp

**Comment by tmalbonph** [comment]
@hcho3

The fix is very simple.
I just inserted the following CMake directives

```gedit
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
if (USE_OPENMP)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
endif (USE_OPENMP)
```

starting at line number 9 on [CMakeLists.txt](https://github.com/dmlc/xgboost/blob/77c03538b0db2e3608ef07ddcf9b48325584dbee/CMakeLists.txt)

```bash
/Users/test/xgboost/linux_x64$ cmake ..

#-- /Users/test/xgboost/dmlc-core/cmake/build_config.h.in -> /Users/test/xgboost/dmlc-core/include/dmlc/build_config.h
#-- Configuring done
#-- Generating done
#-- Build files have been written to: /Users/test/xgboost/linux_x64

make --jobs=2 > /Users/test/xgboost-error-2.log 2>&1 &
tail -f /Users/test/xgboost-error-2.log
#[  1%] Building CXX object CMakeFiles/rabit.dir/rabit/src/allreduce_base.cc.o
#...
#[ 13%] Linking CXX static library librabit.a
#[ 13%] Built target rabit
#[ 32%] Built target dmlc
#...
#[ 70%] Building CXX object src/CMakeFiles/objxgboost.dir/learner.cc.o
#...
#[ 95%] Built target objxgboost
#[ 98%] Building CXX object CMakeFiles/runxgboost.dir/src/cli_main.cc.o
#[ 98%] Linking CXX shared library ../lib/libxgboost.so
#[ 98%] Built target xgboost
#[100%] Linking CXX executable ../xgboost
#[100%] Built target runxgboost
### Press Ctrl-C
ls -altFS ../xgboost
#-rwxrwxr-x 1 test test 3856160 Apr 30 07:07 ../xgboost*
- see included "xgboost-error-2.log"
[xgboost-error-2.log](https://github.com/dmlc/xgboost/files/3129466/xgboost-error-2.log)

**Comment by tmalbonph** [comment]
Here is the new log file [xgboost-error-2.log](https://github.com/dmlc/xgboost/files/3129473/xgboost-error-2.log)

**Comment by hcho3** [comment]
@tmalbonph It's not that simple, since `-fopenmp` flag doesn't work on Windows. The real problem is that older versions of CMake doesn't automatically insert correct flags for OpenMP when OpenMP is used.

**Comment by tmalbonph** [comment]
@hcho3 
If user does not want `OpenMP` support, the fix will still work because it has `if (USE_OPENMP)`

**Comment by hcho3** [comment]
@tmalbonph No, since Windows uses a different flag for OpenMP (`/openmp`).

**Comment by hcho3** [comment]
Working on a fix that works across platforms

**Comment by tmalbonph** [comment]
@hcho3 
On OS that support pthread, they will encounter the pthread_create error.
see line 784 on the provided xgboost-error-1.log
```gedit
io.cc:(.text._ZN4dmlc2io16CachedInputSplit15InitPreprocIterEv[_ZN4dmlc2io16CachedInputSplit15InitPreprocIterEv]+0x89d): undefined reference to `pthread_create'
```

**Comment by tmalbonph** [comment]
@hcho3
For your reference: I did forgot to mention I am using the following:

```bash
cmake --version
#cmake version 3.5.1
#CMake suite maintained and supported by Kitware (kitware.com/cmake).

ls -altFS /usr/bin/cmake
#-rwxr-xr-x 1 root root 4287920 Sep 27  2016 /usr/bin/cmake*

md5sum /usr/bin/cmake
#fb38ba1d24ea6237c9e7400a5f606c0e  /usr/bin/cmake
```

**Comment by hcho3** [comment]
@tmalbonph The fix is available at #4419. Thanks for the report.

**Comment by tmalbonph** [comment]
@hcho3 
Thank you for fixing this issue
