### ISSUE TITLE
when i try make, i get the error, thx for your reply

### ISSUE THREAD

**Issue by sunyinhui** [dmlc/xgboost#4775]
[root@iZbp17euuofuecjbal4r90Z xgboost]# make
Makefile:31: MAKE [make] - checked OK
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -fPIC -DDISABLE_OPENMP -MM -MT build/tree/tree_model.o src/tree/tree_model.cc >build/tree/tree_model.d
g++ -c -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -fPIC -DDISABLE_OPENMP src/tree/tree_model.cc -o build/tree/tree_model.o
src/tree/tree_model.cc: In constructor ‘xgboost::GraphvizGenerator::GraphvizGenerator(const xgboost::FeatureMap&, const string&, bool)’:
src/tree/tree_model.cc:465:55: error: invalid initialization of non-const reference of type ‘std::stringstream& {aka std::basic_stringstream<char>&}’ from an rvalue of type ‘<brace-enclosed initializer list>’
       TreeGenerator(fmap, with_stats), ss_{SuperT::ss_} {
                                                       ^
make: *** [build/tree/tree_model.o] Error 1

**Comment by hcho3** [comment]
It looks like you are using an old version of GCC. We require GCC 5 or later.

**Comment by sunyinhui** [comment]
when i update gcc to 5.5.0, the error is reappear？


[root@localhost xgboost]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc/bin/../libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/usr/local/gcc5.5 --enable-bootstrap --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 5.5.0 (GCC)

**Comment by trivialfis** [comment]
Let me revise that initialization.  Seems it breaking some compilers
